
baseurl: 
# Site settings
title: Chemical Corp Pvt Ltd
logo: /img/logo.png
email: your-email@domain.com
description: "DESCRIBE YOUR PRODUCT"

enquiryemail: enquiry@chemcorp.in

links:
  - title: Aboutus
    # sublinks:
    #   - title: Introduction
    #     path: /pages/aboutus/introduction
    #   - title: Team
    #     path: /pages/aboutus/team
    #   - title: Vision
    #     path: /pages/aboutus/vision
    id: aboutus
  - title: Products
    id: products
  - title: Contact Us
    id: contactus
    


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


industries:
  - title: PHARMA
    image: 'pharma.jpeg'
    id: 1
    products: [ 
      ACETONITRILE,
      ALLYL CHLORIDE,
      ANILINE,
      CHLOROFORM,  
      D M F, 
      DI ISO PROPYLETHER, 
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN,
      GLYCERIN -USP,
      HEPTANE,
      HYDRAZINE HYDRATE,
      HYDROXYLAMINE SULPHATE,
      N PROPANOL, 
      O N  T, 
      PHENOL,
      SUCCINIC ACID,  
      TERTIARY BUTANOL,
      TETRAHYDROFURAN 
    ]
  - title: Adhesives
    image: 'adhesive.jpeg'
    id: 2
    products: [ 
      2 ETHYL HEXANOIC ACID  (S),
      ACRYLAMIDE,
      ALLYL CHLORIDE,
      BUTYL CARBITOL, 
      CYCLO HEXANONE,
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN, 
      FORMIC ACID,
      GLYCERIN -USP,
      HEPTANE,
      Methyl methacrylate (S),
      MYRISTIC ACID (S),
      OLEIC ACID  (S),
      PALMITIC ACID,
      PENTAERYTHRITOL,
      PROPYLENE CARBONATE (S),
      REFINED NAPHTHALENE (S),
      TETRAHYDROFURAN,
      TRICHLORO ETHYLENE, 
      TRIETHANOLAMINE 85,
      TRIMETHYLOL PROPANE,
    ]
  - title: Paints and coatings
    image: 'paint.jpeg'
    id: 3
    products: [
      2 ETHYL HEXANOIC ACID, 
      ACRYLAMIDE,
      ACRYLIC ACID,
      ALLYL CHLORIDE,
      CYCLO HEXANONE,
      CYCLO HEXYLAMINE,
      DI ISO PROPYLETHER, 
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN, 
      GLYCERIN -USP,
      HEPTANE,
      Methyl methacrylate,
      N PROPANOL,
      NEOPENTYL GLYCOL,
      NONYL PHENOL,
      OLEIC ACID,  
      PENTAERYTHRITOL,
      PHTHALIC ANHYDRIDE,
      PROPYLENE CARBONATE,
      REFINED NAPHTHALENE,
      TETRAHYDROFURAN,
      TRIMETHYLOL PROPANE
    ]
  - title: Agro
    image: 'agro.jpg'
    id: 4
    products: [
        ACETONITRILE,
        ANILINE,
        CYCLO HEXANONE,
        FORMIC ACID,
        GLYCERIN -USP,
        HEPTANE,
        HYDRAZINE HYDRATE,
        MONOETHANOL AMINE (Fertilisers),
        MYRISTIC ACID,
        NONYL PHENOL (pesticides),
        O N  T,
        PALMITIC ACID,
        PHOSPHORUS PENTOXIDE (pesticides),
        REFINED NAPHTHALENE, 
        TRICHLORO ETHYLENE,
        TRIETHANOLAMINE 85
      ]
  - title: Fuel and fuel add
    image: 'fuel.jpg'
    id: 5
    products: [
      DI ISO PROPYLETHER, 
      GLYCERIN -USP,
      TERTIARY BUTANOL
    ]

